name: NutriWise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/profile.jpg
    - assets/apple.jpg
    - assets/salad.jpg
    - assets/soup.jpg
    - assets/pumpkin.jpg
    - assets/hot_chocolate.jpg
    - assets/logo.png
    - assets/login_bg.jpg
    # Categories
    - assets/categories/Beverages/beverages.jpg
    - assets/categories/Snacks/snacks.jpg
    - assets/categories/Dairy/dairy.jpg
    - assets/categories/Staples/staples.jpg
    - assets/categories/Canned/canned.jpg
    - assets/categories/Spices/spices.jpg

    # CATEGORY 1 BEVERAGES
    # Coffee
    - assets/categories/Beverages/Coffee/Basilio_Coffee.jpg
    - assets/categories/Beverages/Coffee/SGD_Coffee.png
    - assets/categories/Beverages/Coffee/Bos_Coffee.png
    # Green Tea
    - assets/categories/Beverages/Green_Tea/Yogi_Green_Tea.jpg
    - assets/categories/Beverages/Green_Tea/Twinings_Green_Tea.png
    - assets/categories/Beverages/Green_Tea/Lipton_Matcha.jpg
    # Orange Juice
    - assets/categories/Beverages/Orange_Juice/Tropicana_Pure.jpg
    - assets/categories/Beverages/Orange_Juice/Floridas_Natural.jpg
    - assets/categories/Beverages/Orange_Juice/Locally_Blended.jpg
    # Sparkling Water
    - assets/categories/Beverages/Sparkling_Water/San_Pellegrino.jpg
    - assets/categories/Beverages/Sparkling_Water/Perrier.jpg
    - assets/categories/Beverages/Sparkling_Water/Natures_Spring.jpg
    # Almond Milk
    - assets/categories/Beverages/Almond_Milk/Alpro_Almond_Milk.jpg
    - assets/categories/Beverages/Almond_Milk/Pacific_Foods.jpg
    - assets/categories/Beverages/Almond_Milk/Almond_Breeze.jpg

    # CATEGORY 2 SNACKS
    # Pretzels
    - assets/categories/Snacks/Pretzels/Annies_Organic_Pretzel_Bunnies.jpg
    - assets/categories/Snacks/Pretzels/Synders_Pretzel.jpg
    - assets/categories/Snacks/Pretzels/Trader_Joes_Honey_Wheat_Pretzels.jpg
    # Trail Mix
    - assets/categories/Snacks/Trail_Mix/Take_Root_Banana_Cacao_Trail_Mix.jpg
    - assets/categories/Snacks/Trail_Mix/Nuts_&_Glory_Trail_Mix.png
    - assets/categories/Snacks/Trail_Mix/Trophy_Farms_Trail_Mix.jpg
    # Granola Bars
    - assets/categories/Snacks/Granola_Bars/Kind_Bars.jpg
    - assets/categories/Snacks/Granola_Bars/Nature_Valley_Crunchy_Granola_Bars.jpg
    - assets/categories/Snacks/Granola_Bars/Take_Root_Energy_Bars.jpg
    # Popcorn
    - assets/categories/Snacks/Popcorn/Boom_Chicka_Pop.jpg
    - assets/categories/Snacks/Popcorn/Lesser_Evil_Himalayan_Pink_Salt_Popcorn.jpg
    - assets/categories/Snacks/Popcorn/Skinny_Pop_Original.jpg
    # Dark Chocolate
    - assets/categories/Snacks/Dark_Chocolate/Theo_Organic_85%_Dark_Chocolate.jpg
    - assets/categories/Snacks/Dark_Chocolate/Risa_Chocolates.jpg
    - assets/categories/Snacks/Dark_Chocolate/Malagos_Dark_Chocolate.jpg

    # CATEGORY 5 CANNED GOODS
    # Corn
    - assets/categories/Canned/Corn/Del_Monte_Whole_Kernel_Corn.jpg
    - assets/categories/Canned/Corn/Green_Giant_Whole_Kernel_Sweet_Corn.jpg
    - assets/categories/Canned/Corn/Jolly_Corn_Kernels.jpg
    # Black Beans
    - assets/categories/Canned/Black_Beans/Bushs_Best_Black_Beans.jpg
    - assets/categories/Canned/Black_Beans/Goya_Black_Beans.jpg
    - assets/categories/Canned/Black_Beans/Jolly_Salted_Black_Beans.jpg
    # Coconut Milk
    - assets/categories/Canned/Coconut_Milk/Fiesta_Coconut_Milk.jpg
    - assets/categories/Canned/Coconut_Milk/Kara_Coconut_Milk.jpg
    - assets/categories/Canned/Coconut_Milk/Thai_Kitchen_Organic_Coconut_Milk.jpg
    # Tomato Paste
    - assets/categories/Canned/Tomato_Paste/Del_Monte_Tomato_Paste.png
    - assets/categories/Canned/Tomato_Paste/Hunts_Tomato_Paste.jpg
    - assets/categories/Canned/Tomato_Paste/Muir_Glen_Organic_Tomato_Paste.jpg
    # Tuna
    - assets/categories/Canned/Tuna/Ayam_Brand_Tuna_Chunks.jpg
    - assets/categories/Canned/Tuna/Century_Tuna_Flakes_in_Water.jpg
    - assets/categories/Canned/Tuna/San_Marino_Tuna_Light.jpg


  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
